name: test-all
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: ${{matrix.os}}-${{github.workflow}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v3
      - name: Setup-MSBuild
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Configure
        run: cmake -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=${{matrix.build_type}} -D C_CODE_SAMPLES_WITH_EXTRAS=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

